#!/usr/bin/env bash

echo
cd ${0%/*}
mkdir -p .releases
get_prop() { sed -n "s/^$1=//p" module.prop; }
zip -r9u .releases/$(get_prop id)-$(get_prop version).zip * .gitattributes .gitignore | grep . && echo
